// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjbM_BJR-JdcVW-RgGQtQcCG8aBofk89I',
    appId: '1:597252944089:web:e7b3264245d7ec7f538ec8',
    messagingSenderId: '597252944089',
    projectId: 'lactaamor-de5cd',
    authDomain: 'lactaamor-de5cd.firebaseapp.com',
    storageBucket: 'lactaamor-de5cd.firebasestorage.app',
    measurementId: 'G-6V6NTM2DK9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAL8FIMfDcHMUOACzBZ7cMc7MYGXAsCSWE',
    appId: '1:597252944089:android:42ee09a776e9207b538ec8',
    messagingSenderId: '597252944089',
    projectId: 'lactaamor-de5cd',
    storageBucket: 'lactaamor-de5cd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-3TvYfE79uHXzm2ZLdM_L6L8sk6xAFwg',
    appId: '1:597252944089:ios:f029b61b2920b0bb538ec8',
    messagingSenderId: '597252944089',
    projectId: 'lactaamor-de5cd',
    storageBucket: 'lactaamor-de5cd.firebasestorage.app',
    androidClientId: '597252944089-3k0n4o8o8rihuf075elvqqfo7s12vpb1.apps.googleusercontent.com',
    iosClientId: '597252944089-8mb7teu5qf5qnp1e8i1fa5hsl60ngulf.apps.googleusercontent.com',
    iosBundleId: 'com.example.lactaamor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-3TvYfE79uHXzm2ZLdM_L6L8sk6xAFwg',
    appId: '1:597252944089:ios:f029b61b2920b0bb538ec8',
    messagingSenderId: '597252944089',
    projectId: 'lactaamor-de5cd',
    storageBucket: 'lactaamor-de5cd.firebasestorage.app',
    androidClientId: '597252944089-3k0n4o8o8rihuf075elvqqfo7s12vpb1.apps.googleusercontent.com',
    iosClientId: '597252944089-8mb7teu5qf5qnp1e8i1fa5hsl60ngulf.apps.googleusercontent.com',
    iosBundleId: 'com.example.lactaamor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjbM_BJR-JdcVW-RgGQtQcCG8aBofk89I',
    appId: '1:597252944089:web:853bb571c2b03715538ec8',
    messagingSenderId: '597252944089',
    projectId: 'lactaamor-de5cd',
    authDomain: 'lactaamor-de5cd.firebaseapp.com',
    storageBucket: 'lactaamor-de5cd.firebasestorage.app',
    measurementId: 'G-JB0BWD547R',
  );

}