final List<Map<String, dynamic>> alertas = [
  {
    "id": "presion_alta",
    "tipo": "embarazo",
    "categoria": "madre",
    "nivel": "alto",
    "campo": "presion_sistolica",
    "condicion": ">=",
    "valor": 140,
    "titulo": "Presión arterial alta",
    "mensaje":
        "Tu presión arterial está elevada. Consulta con un profesional de salud.",
    "icono": "warning",
  },
  {
    "id": "presion_muy_alta",
    "tipo": "embarazo",
    "categoria": "madre",
    "nivel": "critico",
    "campo": "presion_sistolica",
    "condicion": ">=",
    "valor": 160,
    "titulo": "Presión peligrosamente alta",
    "mensaje":
        "Tu presión arterial es muy alta. Busca atención médica lo antes posible.",
    "icono": "error",
  },
  {
    "id": "pocos_movimientos_fetales",
    "tipo": "embarazo",
    "categoria": "bebe",
    "nivel": "alto",
    "campo": "movimientos_fetales",
    "condicion": "<=",
    "valor": 3,
    "titulo": "Pocos movimientos del bebé",
    "mensaje":
        "Has registrado pocos movimientos fetales hoy. Si continúa así, consulta con tu médico.",
    "icono": "warning",
  },
  {
    "id": "poco_sueno_embarazo",
    "tipo": "embarazo",
    "categoria": "madre",
    "nivel": "medio",
    "campo": "horas_sueno",
    "condicion": "<",
    "valor": 4,
    "titulo": "Poco descanso",
    "mensaje":
        "Dormir poco puede afectar tu bienestar. Intenta descansar más hoy.",
    "icono": "info",
  },

  {
    "id": "fiebre_bebe",
    "tipo": "postparto",
    "categoria": "bebe",
    "nivel": "critico",
    "campo": "temperatura_bebe",
    "condicion": ">=",
    "valor": 38,
    "titulo": "Fiebre en el bebé",
    "mensaje": "La temperatura del bebé es alta. Busca atención médica.",
    "icono": "error",
  },
  {
    "id": "pocos_panales",
    "tipo": "postparto",
    "categoria": "bebe",
    "nivel": "alto",
    "campo": "panales_mojados",
    "condicion": "<",
    "valor": 4,
    "titulo": "Pocos pañales mojados",
    "mensaje":
        "El bebé ha mojado pocos pañales hoy. Podría indicar deshidratación o poca alimentación.",
    "icono": "warning",
  },
  {
    "id": "poco_sueno_madre",
    "tipo": "postparto",
    "categoria": "madre",
    "nivel": "medio",
    "campo": "horas_sueno_madre",
    "condicion": "<",
    "valor": 3,
    "titulo": "Descanso insuficiente",
    "mensaje": "Has dormido muy poco. Intenta descansar cuando el bebé duerma.",
    "icono": "info",
  },
  {
    "id": "estres_alto",
    "tipo": "postparto",
    "categoria": "madre",
    "nivel": "medio",
    "campo": "nivel_estres",
    "condicion": ">=",
    "valor": 8,
    "titulo": "Nivel de estrés alto",
    "mensaje":
        "Tu nivel de estrés es elevado. Considera buscar apoyo o descansar.",
    "icono": "warning",
  },
];
