final List<Map<String, dynamic>> cuidadosRN = [
  // ================= Lactancia y alimentación =================
  {
    "titulo": "Alimenta a tu bebé cada 2-3 horas",
    "descripcion": "Alimenta a tu bebé frecuentemente para estimular la leche.",
    "edadMinDias": 0,
    "edadMaxDias": 30,
    "categoria": "lactancia",
    "articuloId": "42",
  },
  {
    "titulo": "Prioriza la lactancia materna exclusiva",
    "descripcion": "Evita dar agua o jugos durante los primeros 6 meses.",
    "edadMinDias": 0,
    "edadMaxDias": 180,
    "categoria": "lactancia",
    "articuloId": "43",
  },
  {
    "titulo": "Registra las tomas de tu bebé",
    "descripcion": "Lleva un registro para identificar patrones de hambre.",
    "edadMinDias": 0,
    "edadMaxDias": 30,
    "categoria": "lactancia",
    "articuloId": "44",
  },
  {
    "titulo": "Asegura una posición cómoda para amamantar",
    "descripcion": "Evita dolor y favorece que el bebé succione bien.",
    "edadMinDias": 0,
    "edadMaxDias": 30,
    "categoria": "lactancia",
    "articuloId": "45",
  },
  {
    "titulo": "Estimula suavemente la succión de tu bebé",
    "descripcion":
        "Si el bebé se cansa, masajea suavemente su mandíbula y mejillas.",
    "edadMinDias": 0,
    "edadMaxDias": 30,
    "categoria": "lactancia",
    "articuloId": "46",
  },

  // ================= Sueño seguro =================
  {
    "titulo": "Acuesta a tu bebé boca arriba para dormir",
    "descripcion": "Reduce el riesgo de muerte súbita.",
    "edadMinDias": 0,
    "edadMaxDias": 365,
    "categoria": "sueno",
    "articuloId": "47",
  },
  {
    "titulo": "Asegura una cuna firme y segura",
    "descripcion": "Evita colchones blandos y almohadas.",
    "edadMinDias": 0,
    "edadMaxDias": 365,
    "categoria": "sueno",
    "articuloId": "48",
  },
  {
    "titulo": "Evita mantas sueltas en la cuna",
    "descripcion": "Usa sacos de dormir para bebés.",
    "edadMinDias": 0,
    "edadMaxDias": 365,
    "categoria": "sueno",
    "articuloId": "49",
  },
  {
    "titulo": "Mantén un ambiente tranquilo para dormir",
    "descripcion": "Mantén luz tenue y ruido bajo para dormir mejor.",
    "edadMinDias": 0,
    "edadMaxDias": 365,
    "categoria": "sueno",
    "articuloId": "50",
  },
  {
    "titulo": "Revisa a tu bebé durante la noche",
    "descripcion": "Revisa al bebé regularmente durante los primeros días.",
    "edadMinDias": 0,
    "edadMaxDias": 30,
    "categoria": "sueno",
    "articuloId": "51",
  },

  // ================= Higiene y baño =================
  {
    "titulo": "Mantén limpio y seco el cordón umbilical",
    "descripcion": "Mantén el cordón limpio y seco hasta que caiga solo.",
    "edadMinDias": 0,
    "edadMaxDias": 10,
    "categoria": "higiene",
    "articuloId": "52",
  },
  {
    "titulo": "Realiza un baño suave con agua tibia",
    "descripcion": "Usa agua tibia y jabón neutro 2-3 veces por semana.",
    "edadMinDias": 0,
    "edadMaxDias": 30,
    "categoria": "higiene",
    "articuloId": "53",
  },
  {
    "titulo": "Cambia el pañal con frecuencia",
    "descripcion": "Evita irritaciones y dermatitis.",
    "edadMinDias": 0,
    "edadMaxDias": 30,
    "categoria": "higiene",
    "articuloId": "54",
  },
  {
    "titulo": "Seca bien los pliegues de la piel",
    "descripcion": "Evita humedad en cuello, axilas y área del pañal.",
    "edadMinDias": 0,
    "edadMaxDias": 30,
    "categoria": "higiene",
    "articuloId": "55",
  },
  {
    "titulo": "Usa productos suaves para la piel del bebé",
    "descripcion": "Usa productos suaves recomendados para bebés.",
    "edadMinDias": 0,
    "edadMaxDias": 30,
    "categoria": "higiene",
    "articuloId": "56",
  },

  // ================= Desarrollo y estimulación =================
  {
    "titulo": "Practica el contacto piel con piel",
    "descripcion": "Favorece vínculo y regula temperatura y respiración.",
    "edadMinDias": 0,
    "edadMaxDias": 30,
    "categoria": "desarrollo",
    "articuloId": "57",
  },
  {
    "titulo": "Estimula la vista con objetos de alto contraste",
    "descripcion": "Muéstrale objetos de alto contraste.",
    "edadMinDias": 15,
    "edadMaxDias": 60,
    "categoria": "desarrollo",
    "articuloId": "58",
  },
  {
    "titulo": "Háblale y cántale a tu bebé",
    "descripcion": "Habla y canta suavemente al bebé.",
    "edadMinDias": 0,
    "edadMaxDias": 30,
    "categoria": "desarrollo",
    "articuloId": "59",
  },
  {
    "titulo": "Realiza movimientos suaves con sus brazos y piernas",
    "descripcion":
        "Mueve brazos y piernas suavemente para desarrollar coordinación.",
    "edadMinDias": 15,
    "edadMaxDias": 60,
    "categoria": "desarrollo",
    "articuloId": "60",
  },
  {
    "titulo": "Juega con juguetes seguros y sencillos",
    "descripcion": "Usa sonajeros o juguetes seguros para estimular sentidos.",
    "edadMinDias": 30,
    "edadMaxDias": 90,
    "categoria": "desarrollo",
    "articuloId": "61",
  },
];
