final List<Map<String, dynamic>> cuidadosRN = [
  // ================= Lactancia y alimentación =================
  {
    "titulo": "Alimentar cada 2-3 horas",
    "descripcion": "Alimenta a tu bebé frecuentemente para estimular la leche.",
    "edadMinDias": 0,
    "edadMaxDias": 30,
    "categoria": "lactancia",
    "articuloId": "42",
  },
  {
    "titulo": "Lactancia exclusiva si aplica",
    "descripcion": "Evita dar agua o jugos durante los primeros 6 meses.",
    "edadMinDias": 0,
    "edadMaxDias": 180,
    "categoria": "lactancia",
    "articuloId": "43",
  },
  {
    "titulo": "Registrar tomas",
    "descripcion": "Lleva un registro para identificar patrones de hambre.",
    "edadMinDias": 0,
    "edadMaxDias": 30,
    "categoria": "lactancia",
    "articuloId": "44",
  },
  {
    "titulo": "Posición correcta al amamantar",
    "descripcion": "Evita dolor y favorece que el bebé succione bien.",
    "edadMinDias": 0,
    "edadMaxDias": 30,
    "categoria": "lactancia",
    "articuloId": "45",
  },
  {
    "titulo": "Estimular succión",
    "descripcion":
        "Si el bebé se cansa, masajea suavemente su mandíbula y mejillas.",
    "edadMinDias": 0,
    "edadMaxDias": 30,
    "categoria": "lactancia",
    "articuloId": "46",
  },

  // ================= Sueño seguro =================
  {
    "titulo": "Dormir boca arriba",
    "descripcion": "Reduce el riesgo de muerte súbita.",
    "edadMinDias": 0,
    "edadMaxDias": 365,
    "categoria": "sueno",
    "articuloId": "47",
  },
  {
    "titulo": "Cuna firme y segura",
    "descripcion": "Evita colchones blandos y almohadas.",
    "edadMinDias": 0,
    "edadMaxDias": 365,
    "categoria": "sueno",
    "articuloId": "48",
  },
  {
    "titulo": "Evitar mantas sueltas",
    "descripcion": "Usa sacos de dormir para bebés.",
    "edadMinDias": 0,
    "edadMaxDias": 365,
    "categoria": "sueno",
    "articuloId": "49",
  },
  {
    "titulo": "Ambiente tranquilo",
    "descripcion": "Mantén luz tenue y ruido bajo para dormir mejor.",
    "edadMinDias": 0,
    "edadMaxDias": 365,
    "categoria": "sueno",
    "articuloId": "50",
  },
  {
    "titulo": "Supervisión nocturna",
    "descripcion": "Revisa al bebé regularmente durante los primeros días.",
    "edadMinDias": 0,
    "edadMaxDias": 30,
    "categoria": "sueno",
    "articuloId": "51",
  },

  // ================= Higiene y baño =================
  {
    "titulo": "Limpieza del cordón umbilical",
    "descripcion": "Mantén el cordón limpio y seco hasta que caiga solo.",
    "edadMinDias": 0,
    "edadMaxDias": 10,
    "categoria": "higiene",
    "articuloId": "52",
  },
  {
    "titulo": "Baño suave",
    "descripcion": "Usa agua tibia y jabón neutro 2-3 veces por semana.",
    "edadMinDias": 0,
    "edadMaxDias": 30,
    "categoria": "higiene",
    "articuloId": "53",
  },
  {
    "titulo": "Cambio de pañal frecuente",
    "descripcion": "Evita irritaciones y dermatitis.",
    "edadMinDias": 0,
    "edadMaxDias": 30,
    "categoria": "higiene",
    "articuloId": "54",
  },
  {
    "titulo": "Secar pliegues de la piel",
    "descripcion": "Evita humedad en cuello, axilas y área del pañal.",
    "edadMinDias": 0,
    "edadMaxDias": 30,
    "categoria": "higiene",
    "articuloId": "55",
  },
  {
    "titulo": "Evitar cremas fuertes",
    "descripcion": "Usa productos suaves recomendados para bebés.",
    "edadMinDias": 0,
    "edadMaxDias": 30,
    "categoria": "higiene",
    "articuloId": "56",
  },

  // ================= Desarrollo y estimulación =================
  {
    "titulo": "Contacto piel con piel",
    "descripcion": "Favorece vínculo y regula temperatura y respiración.",
    "edadMinDias": 0,
    "edadMaxDias": 30,
    "categoria": "desarrollo",
    "articuloId": "57",
  },
  {
    "titulo": "Estimulación visual",
    "descripcion": "Muéstrale objetos de alto contraste.",
    "edadMinDias": 15,
    "edadMaxDias": 60,
    "categoria": "desarrollo",
    "articuloId": "58",
  },
  {
    "titulo": "Estimulación auditiva",
    "descripcion": "Habla y canta suavemente al bebé.",
    "edadMinDias": 0,
    "edadMaxDias": 30,
    "categoria": "desarrollo",
    "articuloId": "59",
  },
  {
    "titulo": "Movimientos suaves",
    "descripcion":
        "Mueve brazos y piernas suavemente para desarrollar coordinación.",
    "edadMinDias": 15,
    "edadMaxDias": 60,
    "categoria": "desarrollo",
    "articuloId": "60",
  },
  {
    "titulo": "Juegos simples",
    "descripcion": "Usa sonajeros o juguetes seguros para estimular sentidos.",
    "edadMinDias": 30,
    "edadMaxDias": 90,
    "categoria": "desarrollo",
    "articuloId": "61",
  },
];
