final List<Map<String, dynamic>> recetas = [
  // ===================== MADRE =====================
  {
    "id": "madre_01",
    "titulo": "Sopa de quinua con verduras",
    "descripcion": "Ayuda a recuperar energía y favorece la lactancia.",
    "imagen": "https://link-a-la-imagen.com/sopa_quinua.jpg",
    "seccion": "madre",
    "edadMinDias": null,
    "edadMaxDias": null,
    "condicion": null,
    "articuloId": "62",
  },
  {
    "id": "madre_02",
    "titulo": "Estofado de pollo con verduras",
    "descripcion":
        "Aporta proteínas y vitaminas esenciales para la recuperación.",
    "imagen": "https://link-a-la-imagen.com/estofado_pollo.jpg",
    "seccion": "madre",
    "edadMinDias": null,
    "edadMaxDias": null,
    "condicion": null,
    "articuloId": "63",
  },
  {
    "id": "madre_03",
    "titulo": "Tallarines verdes con pescado",
    "descripcion": "Rico en hierro y ácidos grasos esenciales.",
    "imagen": "https://link-a-la-imagen.com/tallarines_verdes.jpg",
    "seccion": "madre",
    "edadMinDias": null,
    "edadMaxDias": null,
    "condicion": null,
    "articuloId": "64",
  },
  {
    "id": "madre_04",
    "titulo": "Causa de atún saludable",
    "descripcion": "Aporta proteínas y es ligera para el estómago.",
    "imagen": "https://link-a-la-imagen.com/causa_atun.jpg",
    "seccion": "madre",
    "edadMinDias": null,
    "edadMaxDias": null,
    "condicion": null,
    "articuloId": "65",
  },
  {
    "id": "madre_05",
    "titulo": "Arroz con pollo integral",
    "descripcion": "Versión saludable para mejorar energía y digestión.",
    "imagen": "https://link-a-la-imagen.com/arroz_pollo.jpg",
    "seccion": "madre",
    "edadMinDias": null,
    "edadMaxDias": null,
    "condicion": null,
    "articuloId": "66",
  },
  {
    "id": "madre_06",
    "titulo": "Papa a la huancaína ligera",
    "descripcion": "Fuente de carbohidratos y calcio.",
    "imagen": "https://link-a-la-imagen.com/papa_huancaina.jpg",
    "seccion": "madre",
    "edadMinDias": null,
    "edadMaxDias": null,
    "condicion": null,
    "articuloId": "67",
  },
  {
    "id": "madre_07",
    "titulo": "Lomo saltado con quinoa",
    "descripcion": "Proteínas + hierro, ideal para madres en recuperación.",
    "imagen": "https://link-a-la-imagen.com/lomo_quinoa.jpg",
    "seccion": "madre",
    "edadMinDias": null,
    "edadMaxDias": null,
    "condicion": null,
    "articuloId": "68",
  },
  {
    "id": "madre_08",
    "titulo": "Ocopa con verduras al vapor",
    "descripcion": "Ligera, nutritiva y rica en vitaminas.",
    "imagen": "https://link-a-la-imagen.com/ocopa_verduras.jpg",
    "seccion": "madre",
    "edadMinDias": null,
    "edadMaxDias": null,
    "condicion": null,
    "articuloId": "69",
  },
  {
    "id": "madre_09",
    "titulo": "Ensalada de quinua con aguaymanto",
    "descripcion": "Antioxidantes y proteínas vegetales para energía.",
    "imagen": "https://link-a-la-imagen.com/ensalada_quinua.jpg",
    "seccion": "madre",
    "edadMinDias": null,
    "edadMaxDias": null,
    "condicion": null,
    "articuloId": "70",
  },
  {
    "id": "madre_10",
    "titulo": "Caldo de gallina con verduras",
    "descripcion": "Reconfortante y nutritivo para recuperación postparto.",
    "imagen": "https://link-a-la-imagen.com/caldo_gallina.jpg",
    "seccion": "madre",
    "edadMinDias": null,
    "edadMaxDias": null,
    "condicion": null,
    "articuloId": "71",
  },

  // ===================== BEBÉ =====================
  {
    "id": "bebe_01",
    "titulo": "Puré de zanahoria y calabaza",
    "descripcion": "Introduce vegetales al bebé de manera segura.",
    "imagen": "https://link-a-la-imagen.com/pure_zanahoria.jpg",
    "seccion": "bebe",
    "edadMinDias": 180,
    "edadMaxDias": 365,
    "condicion": null,
    "articuloId": "72",
  },
  {
    "id": "bebe_02",
    "titulo": "Puré de camote y manzana",
    "descripcion": "Dulce y suave para digestión delicada.",
    "imagen": "https://link-a-la-imagen.com/pure_camote.jpg",
    "seccion": "bebe",
    "edadMinDias": 180,
    "edadMaxDias": 365,
    "condicion": null,
    "articuloId": "73",
  },
  {
    "id": "bebe_03",
    "titulo": "Papilla de plátano y avena",
    "descripcion": "Ideal para desayunos y complementar lactancia.",
    "imagen": "https://link-a-la-imagen.com/papilla_platano.jpg",
    "seccion": "bebe",
    "edadMinDias": 180,
    "edadMaxDias": 365,
    "condicion": null,
    "articuloId": "74",
  },
  {
    "id": "bebe_04",
    "titulo": "Papilla de pera y manzana",
    "descripcion": "Frutas seguras y suaves para bebés.",
    "imagen": "https://link-a-la-imagen.com/papilla_pera.jpg",
    "seccion": "bebe",
    "edadMinDias": 180,
    "edadMaxDias": 365,
    "condicion": null,
    "articuloId": "75",
  },
  {
    "id": "bebe_05",
    "titulo": "Puré de calabacín y papa",
    "descripcion": "Textura suave y digestiva.",
    "imagen": "https://link-a-la-imagen.com/pure_calabacin.jpg",
    "seccion": "bebe",
    "edadMinDias": 180,
    "edadMaxDias": 365,
    "condicion": null,
    "articuloId": "76",
  },
  {
    "id": "bebe_06",
    "titulo": "Papilla de espinaca y papa",
    "descripcion": "Rica en hierro vegetal y vitaminas.",
    "imagen": "https://link-a-la-imagen.com/papilla_espinaca.jpg",
    "seccion": "bebe",
    "edadMinDias": 180,
    "edadMaxDias": 365,
    "condicion": null,
    "articuloId": "77",
  },

  // ===================== CONDICIÓN =====================
  {
    "id": "cond_01",
    "titulo": "Guiso de lentejas con quinua",
    "descripcion": "Rico en hierro para madres con anemia en lactancia.",
    "imagen": "https://link-a-la-imagen.com/guiso_lentejas.jpg",
    "seccion": "condicion",
    "edadMinDias": null,
    "edadMaxDias": null,
    "condicion": "anemiaLactancia",
    "articuloId": "78",
  },
  {
    "id": "cond_02",
    "titulo": "Sopa de espinaca con quinua",
    "descripcion": "Aumenta hierro y vitaminas esenciales.",
    "imagen": "https://link-a-la-imagen.com/sopa_espinaca.jpg",
    "seccion": "condicion",
    "edadMinDias": null,
    "edadMaxDias": null,
    "condicion": "anemiaLactancia",
    "articuloId": "79",
  },
  {
    "id": "cond_03",
    "titulo": "Guiso de sangrecita",
    "descripcion": "Fuente de hierro para recuperación postparto.",
    "imagen": "https://link-a-la-imagen.com/guiso_sangrecita.jpg",
    "seccion": "condicion",
    "edadMinDias": null,
    "edadMaxDias": null,
    "condicion": "anemiaLactancia",
    "articuloId": "80",
  },
  {
    "id": "cond_04",
    "titulo": "Tortilla de quinua y huevo",
    "descripcion": "Aporta proteínas y hierro.",
    "imagen": "https://link-a-la-imagen.com/tortilla_quinua.jpg",
    "seccion": "condicion",
    "edadMinDias": null,
    "edadMaxDias": null,
    "condicion": "anemiaLactancia",
    "articuloId": "81",
  },
  {
    "id": "cond_05",
    "titulo": "Ensalada de lentejas con verduras",
    "descripcion":
        "Ideal para madres en lactancia exclusiva, ligera y nutritiva.",
    "imagen": "https://link-a-la-imagen.com/ensalada_lentejas.jpg",
    "seccion": "condicion",
    "edadMinDias": null,
    "edadMaxDias": null,
    "condicion": "lactanciaExclusiva",
    "articuloId": "82",
  },
  {
    "id": "cond_07",
    "titulo": "Guiso de quinua con hígado",
    "descripcion": "Rico en proteínas y hierro para lactancia exclusiva.",
    "imagen": "https://link-a-la-imagen.com/guiso_higado.jpg",
    "seccion": "condicion",
    "edadMinDias": null,
    "edadMaxDias": null,
    "condicion": "lactanciaExclusiva",
    "articuloId": "83",
  },
  {
    "id": "cond_08",
    "titulo": "Sopa de lentejas con verduras",
    "descripcion": "Nutritiva y ligera, perfecta para lactancia exclusiva.",
    "imagen": "https://link-a-la-imagen.com/sopa_lentejas.jpg",
    "seccion": "condicion",
    "edadMinDias": null,
    "edadMaxDias": null,
    "condicion": "lactanciaExclusiva",
    "articuloId": "84",
  },
];
